services:
  app1:
    command: uvicorn main:app --host '0.0.0.0' --port 5000
    build:
      context: ..
      dockerfile: ./infra/Dockerfile
    restart: always
    ports:
      - "5004:5000"
  postgresql:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
